### ISSUE TITLE
Where are the docs

### ISSUE THREAD

**Issue by vvo** [netlify/docs#14]
Hi, I would like to update the docs and do a PR but:
1. seems like the docs are now hidden somewhere (no big deal)
2. this repo seems dead but does not states it (a bit more frustrating), there's nothing to update here.

Thanks!

**Comment by bdougie** [comment]
Sorry, this is a deprecated location of our docs. We do not publically exposed the docs at the moment. For feel free to open a support issue, though I believe your concern has already been resolved via Twitter :)

I am actively looking for solutions to expose the docs, without exposing the entire repo to the public and open to suggestions.

**Comment by vvo** [comment]
Ok thanks, ultimately we could delete this repo, it's coming in third position for "netlify docs"

**Comment by vvo** [comment]
As for a solution about having public editable docs while keeping some things private, there's no quick win you will have to carefully create something that fits you but overall it's worth it, I would have definitely edited those pages about .ruby-version for you and proposed the change. Which means: free work.

I would say any good dev tooling docs now should have an [EDIT THIS PAGE] publicly available, it shows transparency, trust and care to the user.

But those things takes time, even us we do not YET have EDIT THIS PAGE for every doc at Algolia. We have it for some open source projects still.

cc @maxiloc we need EDIT THIS PAGE publicly for Algolia.com: free work :D
